# -*- coding: utf-8 -*-
"""CS205 Warmup Parsing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zfPjeKIizNaCA5OeNZbQWGdqPy9YdoE
"""

#Prototype of algorithm flow

continue_ = True 

while (continue_ == True):
  val = input("Enter command: ") 
  if (val == "exit"):
    continue_ = False
  elif (val == "help"):
    print("You can enter the following commands: ")
    print("title “movie title” genre")
    print("title “movie title” vote_average")
    print("title “movie title” release_date")
    print("title “movie title” revenue")
    print("title “movie title” production_company")
    print("max_revenue “genre”")
    print("max_rating “genre”")
    print("exit")
  else:
    arg1, arg2, arg3 = val.split('"')
    arg1 = arg1+"x"
    arg3 = "x"+arg3
    arg1, garbage = arg1.split()
    garbage, arg3 = arg3.split()

    if(arg1 == "title"):
       print("Query Input: ", arg1, arg2, arg3)

    elif(arg1 == "max_revenue" || arg1 == "max_rating"):
      print("Query Input: ", arg1, arg2)

if(val == "title"):
  arg1, arg2, arg3 = val.split('"')

if(val == "max_revenue"):
  arg1, arg2 = val.split('"')

#Prototype of algorithm flow

continue_ = True 
database_initialized = False

while (continue_ == True):
  val = input("Enter command: ")
  if (val == "load_data"):
    print("Data loaded")
    database_initialized = True
    val = input("Enter command: ")

  if (database_initialized == False):
    print("Data has not been initialized. Please enter “load_data”") 
  else:
    if (val == "exit"):
      continue_ = False
    elif (val == "help"):
      print("You can enter the following commands: ")
      print("title “movie title” genre")
      print("title “movie title” vote_average")
      print("title “movie title” release_date")
      print("title “movie title” revenue")
      print("title “movie title” production_company")
      print("max_revenue “genre”")
      print("max_rating “genre”")
      print("exit")
    else:
      if(arg1, arg2, arg3 != val.split('"')):
        print(val +" is not a valid input. Please try again or enter “help” for assistance")

      else:
        arg1, arg2, arg3 = val.split('"')
        arg1 = arg1+"x"
        arg3 = "x"+arg3
        arg1, garbage = arg1.split()
        garbage, arg3 = arg3.split()

      if(arg1 == "title"):
        
        if(arg3 == "production_company"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "genre"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "vote_average"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "release_date"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "revenue"):
          print("Query Input: ", arg1, arg2, arg3)
        else:
          print(arg3 +" is not a valid input. Please try again or enter “help” for assistance")

      elif(arg1 == "max_revenue" or arg1 == "max_rating"):
        print("Query Input: ", arg1, arg2)

      else:
        print(arg1 +" is not a valid input. Please try again or enter “help” for assistance")

#Testing database error checking

continue_ = True 
database_initialized = False

while (continue_ == True):
  val = input("Enter command: ")
  if (val == "load_data"):
    print("Data loaded")
    #database_launched = loadData();
    #if (database_launched ==1):
    # print("Database failed to load")
    #else:
    # database_initialized = True
    # val = input("Enter command: ")

  if (database_initialized == False):
    print("Data has not been initialized. Please enter “load_data”") 
  else:
    if (val == "exit"):
      continue_ = False
    elif (val == "help"):
      print("You can enter the following commands: ")
      print("title “movie title” genre")
      print("title “movie title” vote_average")
      print("title “movie title” release_date")
      print("title “movie title” revenue")
      print("title “movie title” production_company")
      print("max_revenue “genre”")
      print("max_rating “genre”")
      print("exit")
    else:
      if(arg1, arg2, arg3 != val.split('"')):
        print(val +" is not a valid input. Please try again or enter “help” for assistance")

      else:
        arg1, arg2, arg3 = val.split('"')
        arg1 = arg1+"x"
        arg3 = "x"+arg3
        arg1, garbage = arg1.split()
        garbage, arg3 = arg3.split()

      if(arg1 == "title"):
        
        if(arg3 == "production_company"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "genre"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "vote_average"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "release_date"):
          print("Query Input: ", arg1, arg2, arg3)
        elif(arg3 == "revenue"):
          print("Query Input: ", arg1, arg2, arg3)
        else:
          print(arg3 +" is not a valid input. Please try again or enter “help” for assistance")

      elif(arg1 == "max_revenue" or arg1 == "max_rating"):
        print("Query Input: ", arg1, arg2)

      else:
        print(arg1 +" is not a valid input. Please try again or enter “help” for assistance")