# -*- coding: utf-8 -*-
"""CS205 Warmup Parsing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zfPjeKIizNaCA5OeNZbQWGdqPy9YdoE
"""
from database import Database
#Testing database error checking

#initializes cases to terminate loop
continue_ = True 
database_initialized = False
db = Database()

#continues to allow user to search until they type exit
while (continue_ == True):
  val = input("Enter command: ")
  words = len(val.split())
  if (val == "exit"):
      continue_ = False
  #ensures that data is loaded
  elif (val == "load data"):
    flag = db.load_data()
    while (flag != 0):
        print("Data initialization failed. Please try again")
        val = input("Enter command: ")
    print("Data loaded")
    database_initialized = True
    val = input("Enter command: ")
    words = len(val.split())

  if (database_initialized == False and continue_==True):
    print("Data has not been initialized. Please enter “load data”") 
  else:
    if (val == "exit"):
      continue_ = False
    elif (val == "help"):
      print("\nYou can enter the following commands: ")
      print("print all titles")
      print("print all companies")
      print("title “movie title” vote_average")
      print("title “movie title” revenue")
      print("title “movie title” proco_name")
      print("title “movie title” proco_location")
      print("max revenue")
      print("max rating")
      print("exit")

    elif(val == "max revenue"):
        print("Query Input: max revenue")
        db.get_max_revenue()

    elif(val == "max rating"):
        print("Query Input: max rating")
        db.get_max_rating()

    elif(val == "print all titles"):
        print("Query Input: print all titles")
        db.print_all_titles()

    elif(val == "print all companies"):
        print("Query Input: print all companies")
        db.print_all_companies()

    elif (words == 1 or words == 2):
        print("Too few or invalid arguments. Please try again\n")

    else:
      #filters data into desired format
      arg1, arg2, arg3 = val.split('"')
      arg1 = arg1+"x"
      arg3 = "x"+arg3
      arg1, garbage = arg1.split()
      garbage, arg3 = arg3.split()

      if(arg1 == "title"):

        if(arg3 == "proco_name"):
          print("Query Input: ", arg1, arg2, arg3)
          db.get_proco_name(arg2)

        elif(arg3 == "proco_location"):
          print("Query Input: ", arg1, arg2, arg3)
          db.get_proco_location(arg2)

        elif(arg3 == "vote_average"):
          print("Query Input: ", arg1, arg2, arg3)
          db.get_vote_average(arg2)

        elif(arg3 == "revenue"):
          print("Query Input: ", arg1, arg2, arg3)
          db.get_revenue(arg2)

        else:
          print(arg3 +" is not a valid input. Please try again or enter “help” for assistance")

      else:
        print(arg1 +" is not a valid input. Please try again or enter “help” for assistance")
